#!/bin/bash
# postinst script for slimbookbattery

#DEBHELPER#

set -e

echo "Debian postinst $1 :"

if python3 /usr/share/slimbookbattery/src/check_config.py; then
  echo 'Configuration OK'
fi

if chmod -R 755 /usr/share/slimbookbattery/src/*.py; then
  echo 'Permissions given.'

fi

if chmod -R 755 /usr/share/slimbookbattery/src/*.sh; then
  echo 'Permissions given.'

fi

# Enabling tlp.service
if sudo systemctl enable tlp.service; then
  echo 'Tlp service enabled'
fi

files=(
/lib/systemd/system/slimbookbattery.service
/home/*/.config/autostart/slimbookbattery-autostart.desktop
)

# Checks if files exist and removes them
for file in ${files[@]}; do
  if test -f $file; then
    rm $file
  fi
done

exit 0
