#!/bin/bash
# postinst script for slimbookbattery

set -e
set -x

python3 /usr/share/slimbookbattery/src/check_config.py

chmod -R 755 /usr/share/slimbookbattery/src/*.py
chmod -R 755 /usr/share/slimbookbattery/src/*.sh

# Enabling tlp.service
sudo systemctl enable tlp.service

files=(
  /lib/systemd/system/slimbookbattery.service 
/home/*/.config/autostart/slimbookbattery-autostart.desktop
)

# Checks if files exist and removes them
for file in ${files[@]}; do
  if test -f $file; then
    rm $file
fi
done



exit 0
