# 00-template.conf - Template for TLP drop-in customizations
# See full explanation: https://linrunner.de/tlp/settings
#
# PARAMETER="value"
# PARAMETER+="add value"


# Operation 

	# TLP_ENABLE=1

	# TLP_WARN_LEVEL=3

	# TLP_DEFAULT_MODE=AC

	# TLP_PERSISTENT_DEFAULT=0

	# TLP_PS_IGNORE="BAT"


# Audio 

	# SOUND_POWER_SAVE_ON_AC=1
	# SOUND_POWER_SAVE_ON_BAT=1

	# SOUND_POWER_SAVE_CONTROLLER=Y


# Battery Care (Not available)

	# START_CHARGE_THRESH_BAT0=75
	# STOP_CHARGE_THRESH_BAT0=80

	# START_CHARGE_THRESH_BAT1=75
	# STOP_CHARGE_THRESH_BAT1=80

	# RESTORE_THRESHOLDS_ON_BAT=1

	# NATACPI_ENABLE=1
	# TPACPI_ENABLE=1
	# TPSMAPI_ENABLE=1

# Drive Bay

	# BAY_POWEROFF_ON_AC=0
	# BAY_POWEROFF_ON_BAT=0

	# BAY_DEVICE=sr0


# Disks and Controllers

	# DISK_DEVICES="nvme0n1 sda"

	# DISK_DEVICES="ata-INTEL_SSDSA2M160G2GC_XZY123456890 ata-HITACHI_HTS541612J9SA00_XZY123456890"

	# DISK_APM_LEVEL_ON_AC="254 254"
	# DISK_APM_LEVEL_ON_BAT="128 128"

	# DISK_APM_CLASS_DENYLIST="usb ieee1394"

	# DISK_SPINDOWN_TIMEOUT_ON_AC="0 0"
	# DISK_SPINDOWN_TIMEOUT_ON_BAT="0 0"

	# DISK_IOSCHED="mq-deadline mq-deadline"

	# SATA_LINKPWR_ON_AC="med_power_with_dipm max_performance"
	# SATA_LINKPWR_ON_BAT="med_power_with_dipm min_power"

	# SATA_LINKPWR_DENYLIST="host1"
 
		# Old value
		# SATA_LINKPWR_BLACKLIST

	# AHCI_RUNTIME_PM_ON_AC=on
	# AHCI_RUNTIME_PM_ON_BAT=auto

	# AHCI_RUNTIME_PM_TIMEOUT=15


# File System

	# DISK_IDLE_SECS_ON_AC=0
	# DISK_IDLE_SECS_ON_BAT=2

	# MAX_LOST_WORK_SECS_ON_AC=15
	# MAX_LOST_WORK_SECS_ON_BAT=60


# Graphics

	# INTEL_GPU_MIN_FREQ_ON_AC=0
	# INTEL_GPU_MIN_FREQ_ON_BAT=0
	# INTEL_GPU_MAX_FREQ_ON_AC=0
	# INTEL_GPU_MAX_FREQ_ON_BAT=0
	# INTEL_GPU_BOOST_FREQ_ON_AC=0
	# INTEL_GPU_BOOST_FREQ_ON_BAT=0

	# RADEON_DPM_PERF_LEVEL_ON_AC=auto
	# RADEON_DPM_PERF_LEVEL_ON_BAT=auto

	# RADEON_DPM_STATE_ON_AC=performance
	# RADEON_DPM_STATE_ON_BAT=battery

	# RADEON_POWER_PROFILE_ON_AC=default
	# RADEON_POWER_PROFILE_ON_BAT=default


# Kernel

	# NMI_WATCHDOG=0


# Networking

	# WIFI_PWR_ON_AC=off
	# WIFI_PWR_ON_BAT=on

	# WOL_DISABLE=Y


# Platform (1.4 +)

	# PLATFORM_PROFILE_ON_AC=performance
	# PLATFORM_PROFILE_ON_BAT=low-power


# Processor

	# CPU_SCALING_GOVERNOR_ON_AC=powersave
	# CPU_SCALING_GOVERNOR_ON_BAT=powersave

	# CPU_SCALING_MIN_FREQ_ON_AC=0
	# CPU_SCALING_MAX_FREQ_ON_AC=9999999
	# CPU_SCALING_MIN_FREQ_ON_BAT=0
	# CPU_SCALING_MAX_FREQ_ON_BAT=9999999

    

	# CPU_ENERGY_PERF_POLICY_ON_AC=balance_performance
	# CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power
	# Old variable
	# CPU_HWP_ON_AC=balance_performance
	# CPU_HWP_ON_BAT=balance_power


	# CPU_MIN_PERF_ON_AC=0
	# CPU_MAX_PERF_ON_AC=100
	# CPU_MIN_PERF_ON_BAT=0
	# CPU_MAX_PERF_ON_BAT=30

	# CPU_BOOST_ON_AC=1
	# CPU_BOOST_ON_BAT=0

	# CPU_HWP_DYN_BOOST_ON_AC=1
	# CPU_HWP_DYN_BOOST_ON_BAT=0

	# SCHED_POWERSAVE_ON_AC=0
	# SCHED_POWERSAVE_ON_BAT=1

	# ENERGY_PERF_POLICY_ON_AC=performance
	# ENERGY_PERF_POLICY_ON_BAT=power

    #intel_pstate-

# Radio Device Switching

	# RESTORE_DEVICE_STATE_ON_STARTUP=0

	# DEVICES_TO_DISABLE_ON_STARTUP="bluetooth wifi wwan"

	# DEVICES_TO_ENABLE_ON_STARTUP="bluetooth wifi wwan"

	# DEVICES_TO_DISABLE_ON_SHUTDOWN="bluetooth wifi wwan"

	# DEVICES_TO_ENABLE_ON_SHUTDOWN="bluetooth wifi wwan"

	# DEVICES_TO_ENABLE_ON_AC="bluetooth wifi wwan"

	# DEVICES_TO_DISABLE_ON_BAT="bluetooth wifi wwan"

	# DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE="bluetooth wifi wwan"


# Radio Device Wizard

	# DEVICES_TO_DISABLE_ON_LAN_CONNECT="wifi wwan"
	# DEVICES_TO_DISABLE_ON_WIFI_CONNECT="wwan"
	# DEVICES_TO_DISABLE_ON_WWAN_CONNECT="wifi"

	# DEVICES_TO_ENABLE_ON_LAN_DISCONNECT="wifi wwan"
	# DEVICES_TO_ENABLE_ON_WIFI_DISCONNECT=""
	# DEVICES_TO_ENABLE_ON_WWAN_DISCONNECT=""

	# DEVICES_TO_ENABLE_ON_DOCK=""
	# DEVICES_TO_DISABLE_ON_DOCK=""

	# DEVICES_TO_ENABLE_ON_UNDOCK="wifi"
	# DEVICES_TO_DISABLE_ON_UNDOCK=""


# Runtime Power Management and ASPM

	# RUNTIME_PM_ON_AC=on
	# RUNTIME_PM_ON_BAT=auto

	# RUNTIME_PM_DENYLIST="11:22.3 44:55.6"
	# RUNTIME_PM_DRIVER_DENYLIST="mei_me nouveau radeon"

		# Old values
		# RUNTIME_PM_BLACKLIST
		# RUNTIME_PM_DRIVER_BLACKLIST 


	# RUNTIME_PM_ENABLE="11:22.3"

	# RUNTIME_PM_DISABLE="44:55.6"

	# PCIE_ASPM_ON_AC=default
	# PCIE_ASPM_ON_BAT=default


### USB

	# USB_AUTOSUSPEND=1

	# USB_DENYLIST="1111:2222 3333:4444"

	# USB_EXCLUDE_AUDIO=1

	# USB_EXCLUDE_BTUSB=1

	# USB_EXCLUDE_PHONE=1

	# USB_EXCLUDE_PRINTER=1

	# USB_EXCLUDE_WWAN=0
 
		# Old values
		# USB_BLACKLIST
		# USB_BLACKLIST_BTUSB
		# USB_BLACKLIST_PHONE
		# USB_BLACKLIST_PRINTER
		# USB_BLACKLIST_WWAN
 
	# USB_ALLOWLIST="5555:6666 7777:8888"
	
 		# Old values are
 		# USB_WHITELIST

	# USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN=1
